sudo: required
services:
  - docker

before_install:
  - docker build -t dddas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dddas/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react
  env: "Docker-env"
  bucket_name: elasticbeanstalk-us-east-1-696690693790
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"